# Platform: NVIDIA Jetson — JetPack 5.x, DeepStream 6.2
# Builds C++ core_engine + Python FastAPI control plane in one image.
# Base image: DeepStream 6.2 Triton (ARM64 / aarch64)
FROM nvcr.io/nvidia/deepstream-l4t:6.2-triton

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# System deps for C++ build + Python layer
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    pkg-config \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libyaml-cpp-dev \
    libzmq3-dev \
    python3-pip \
    python3-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# --- Build C++ core engine ---
COPY core_engine /workspace/core_engine
RUN cd /workspace/core_engine \
    && mkdir -p build \
    && cd build \
    && cmake .. -DDS_SDK_PATH=/opt/nvidia/deepstream/deepstream \
    && make -j$(nproc)

# --- Python FastAPI layer ---
COPY requirements.txt /workspace/requirements.txt
RUN pip3 install --no-cache-dir -r /workspace/requirements.txt

COPY api /workspace/api
COPY start.sh /workspace/start.sh
RUN chmod +x /workspace/start.sh

# Model dirs — bind-mounted at runtime from host (see docker-compose.jetson.yml).
# nvinfer configs reference models as ../../models/ relative to configs/ dir,
# which resolves to /workspace/models/ inside the container — one level above core_engine/.
# The same ../../models/ path also works in standalone mode on the host.
RUN mkdir -p /workspace/models/peoplenet \
             /workspace/models/reid

# Runtime config is generated by camera_registry.py at startup
# Configs (model INI/YML files) are copied from core_engine/configs
EXPOSE 8001

CMD ["/workspace/start.sh"]
